export default {
  lineApplyChart: [],
  lineRegisterChart: [],
  columnMajorChart: [],
  columnProfessorChart: [],
  columnCoworkChart: [],
  tags: {
    nine: [],
    nationalStandard: [],
    ict: [],
    techTheme: [],
    major: [],
    grade: [],
    categoryCount: [],
  },
  tagStatus: {
    stu: 0,
    condition: 'and',
    status: '',
    tag: '',
    major: '',
    grade: '',
    date: '',
  },
  selectedTags: { tagName: [], tagCount: [] },
  fetchedTags: {
    listshow: [],
  },
  selectedList: [],
};
